server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    consumer:
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: 127.0.0.1:9092